name: docdoc_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Animations
  animations: ^2.0.11
  animated_bottom_navigation_bar: ^1.4.0
  shimmer: ^3.0.0
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  flutter_iconly: ^1.0.2
  smooth_page_indicator: ^1.2.1
  ionicons: ^0.2.2

  # Camera & Image
  camera: ^0.11.2
  image_picker: ^1.1.2
  image: ^4.5.4
  gif: ^2.3.0

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Routing
  go_router: ^16.0.0

  # Data
  dio: ^5.8.0+1
  dartz: ^0.10.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  path_provider: ^2.1.5
  uuid: ^4.1.0
  quiver: ^3.2.2

  # Layout & Sizing
  flutter_screenutil: ^5.9.3

  # Preview
  device_preview: ^1.2.0

  # AI Model
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/labels.txt
    - assets/model.tflite
    - assets/emotions_model.tflite
    - assets/labelss.txt

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

flutter_assets:
  assets_path: assets/
  output_path: lib/core/Helpers/
  filename: assets.dart
  field_prefix: images
  classname: Images
