name: docdoc_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+20

environment:
  sdk: ^3.7.2

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  animations: ^2.0.11
  camera: ^0.11.2
  dartz: ^0.10.1
  device_preview: ^1.3.1
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_iconly: ^1.0.2
  flutter_launcher_icons: ^0.14.4
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  get_it: ^8.0.3
  gif: ^2.3.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  image: ^4.5.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  ionicons: ^0.2.2
  path_provider: ^2.1.5
  purchases_flutter: ^9.10.7
  quiver: ^3.2.2
  rename: ^3.1.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  tflite_flutter: ^0.11.0
  uuid: ^4.1.0
  in_app_purchase: ^3.2.3
  url_launcher: ^6.3.0
  

dev_dependencies:
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/appLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/appLogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/appLogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/appLogo.png"
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/langs/
    - assets/labels.txt
    - assets/model.tflite
    - assets/emotions_model.tflite
    - assets/labelss.txt

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

flutter_assets:
  assets_path: assets/
  output_path: lib/core/Helpers/
  filename: assets.dart
  field_prefix: images
  classname: Images
